openapi: 3.0.0
info:
  title: Example App
  description: App for learning Jakarta EE.
  license:
    name: Apache License
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:{port}/learn-jakartaee-jaxrs
  description: Simple Open Liberty
  variables:
    port:
      default: "9080"
      description: Server HTTP port
paths:
  /api/ping:
    get:
      summary: Ping server.
      description: Returns a greeting
      operationId: pingId
      responses:
        200:
          description: Ping server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
components:
  schemas:
    Ping:
      type: object
      properties:
        greeting:
          type: string
      description: Ping response.